pipeline{
    agent any
    stages{
        stage('Code-pull'){
            steps{
                git branch: 'main', url: 'https://github.com/baldevganava260-design/flight-reservation-app.git'
            }
        }
        stage ('Build'){
            steps{
                sh ''
                    cd FlightReservationApplication
                    mvn clean package
                ''
            }
        }
         stage('QA-Test'){
            steps{
                withSonarQubeEnv(installationName: 'sonar', credentialsId: 'sonar-token') {
                  sh''
                     cd FlightReservationApplication
                     mvn sonar:sonar -Dsonar.projectKey=flight-reservation
                  ''
                }
            }
         }
         stage('Docker-build'){
            steps{
                sh''
                   cd FlightReservationApplication
                   docker build -t shinchan260/flight-reservation-15-16:latest .
                   docker push shinchan260/flight-reservation-15-16:latest
                   docker rmi shinchan260/flight-reservation-15-16:latest
                ''      
            }
         }
         stage('Deploy'){
            steps{
                sh''
                    cd FlightReservationApplication
                    kubectl apply -f k8s/
                ''
            }
         }
    }
}
