pipeline{
    agent any 
    stages{
        stage('Code-pull'){
            steps{
                git branch: 'main', url: 'https://github.com/baldevganava260-design/flight-reservation-app.git'
            }
        }
    }
}